### ISSUE TITLE
fix null test

### ISSUE THREAD

**Issue by lloydbenson** [fishin/hatchery#5]
If doing npm test but having lab.json or something theres an uncaught error i need to resolve.

Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'coverage' of null
    at exports.getTestResult (/Users/lbenson/scm/fishin/gills/node_modules/tacklebox/node_modules/bait/node_modules/hatchery/lib/index.js:27:50)
    at Object.exports.getTestResult (/Users/lbenson/scm/fishin/gills/node_modules/tacklebox/node_modules/bait/lib/test.js:14:27)
    at Function.exports.getJobConfig (/Users/lbenson/scm/fishin/gills/lib/utils/job.js:170:63)

**Comment by lloydbenson** [comment]
done
